# Generated by Django 4.2.2 on 2023-06-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot_w', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
