# Generated by Django 4.2.2 on 2023-06-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot_w', '0005_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_db',
        ),
    ]
