# Generated by Django 4.2.2 on 2023-06-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot_w', '0007_alter_user_first_name_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
